= Test d'une carte Electronique (Test In-Situ)
Alex Fabre, Pierre-Alexis Robin, Clément Gandolphe
2019-05-16
:toc:

//http://www.electronique-mag.com/article2125.html

== Tester une carte

Le test de carte électronique repose sur trois types de tests:

- l’inspection visuelle automatique (*AOI*)
- l’inspection à Rayons X (*AXI*)
- le test électrique (*In-Situ* et *fonctionnel*)

=== Contraintes d'aujourd'hui

Les évolutions technologiques font apparaître de nouvelles contraintes:

- *Intégration* : les cartes intègrent de plus en plus de fonctions et de composants. Il est par conséquent de plus en plus difficile d’accéder à toutes les équipotentielles de la carte pour le test In-Situ.
- *Miniaturisation* : les composants sont de plus en plus petits rendant l’inspection visuelle inefficace dans la majorité des cas.
- *Complexité* : des fonctions de plus en plus complexes sont intégrées dans les cartes

== Le test In-Situ

Le test In-Situ se base sur la mesure de tous les équipotentiels de la carte. Pour cela il est nécessaire de prévoir un accès le plus complet aux pistes pour une couverture maximale. Lorsqu'il est bien mené le test In-Situ est considéré comme le plus efficace car il dispose d'avantages importants:

- Rapidité de développement des mécanismes de test
- Vitesse de test
- Possibilité de programmer les composants

Cependant il ne pourra continuer à exister que s'il s'adapte au évolutions technologiques que sont:

- La miniaturisation des composants
- L'accessibilité des circuits

=== Mise en place du test

Il existe différentes méthodes de test:

Pour s'assurer de l'accès au

- _Cover-Extend Technology_: Permet de remplacer l'accès aux pistes au niveau du composant (_Bundary Scan_) par un accès directe sur les connecteurs.
- _Bundary Scan_: Permet de tester les potentiels aux "frontieres" d'un groupe de composants.

